<?php
/**
 * @file
 * Monitoring test bootstrap file.
 */

/**
 * Implements hook_queue_info().
 */
function monitoring_test_queue_info() {
  $queues['monitoring_test'] = array(
    'worker callback' => 'monitoring_test_queue_worker',
    'time' => 60,
  );
  return $queues;
}

/**
 * Dummy worker callback for test queue.
 */
function monitoring_test_queue_worker() {

}

/**
 * Implements hook_commerce_currency_info_alter().
 */
function monitoring_test_commerce_currency_info_alter(&$currencies, $langcode) {
  // Alter CHF currency to use a ' as thousands separator, to verify correct
  // encoding of the status message.
  $currencies['CHF']['decimal_separator'] = '.';
  $currencies['CHF']['thousands_separator'] = '\'';
  $currencies['CHF']['code_placement'] = 'before';
}
